# release.tml

# Global release configurations
publish = false
tag-prefix = "v"
tag-name = "v{{version}}"

# Git-cliff changelog generation for each release
pre-release-hook = ["git-cliff", "--tag", "v{{version}}"]

